name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore shyoon/shyoon.sln
    - name: Build
      run: dotnet build shyoon/shyoon.sln --no-restore
    - name: Test
      run: dotnet test shyoon/shyoon.sln --no-build --verbosity normal
